import React from 'react';
import { useAuth } from '../../app/providers/AuthProvider';
import { PageHeader } from '../../components/common/PageHeader';
import { MetricCard } from '../../components/common/MetricCard';
import { Card, CardHeader } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { AIBadge, StatusBadge } from '../../components/ui/Badge';
import { useNavigate } from 'react-router-dom';
import {
  Layers,
  Image,
  CheckSquare,
  Send,
  Plus,
  ArrowRight,
  Clock,
  Sparkles,
  Lightbulb,
  CheckCircle2,
  TrendingUp
} from 'lucide-react';
import { mockRecommendations, mockAuditLogs } from '../../mock/data';

export const DashboardPage: React.FC = () => {
  const { user, currentBrand } = useAuth();
  const navigate = useNavigate();

  return (
    <div className="space-y-8">
      {/* Top Banner & Header */}
      <PageHeader
        title={`Good morning, ${user?.name.split(' ')[0] || 'Sarah'}`}
        subtitle={`${currentBrand.name} (${currentBrand.location}) — Here's what needs your attention today.`}
        action={
          <Button
            variant="primary"
            size="md"
            leftIcon={<Plus className="w-4 h-4" />}
            onClick={() => navigate('/campaigns/new')}
          >
            Create Campaign
          </Button>
        }
      />

      {/* Metric Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
        <MetricCard
          title="Active Campaigns"
          value="12"
          change="+2 this month"
          changeType="positive"
          icon={<Layers className="w-5 h-5 text-[#173B63]" />}
        />
        <MetricCard
          title="Content Assets"
          value="48"
          change="100% Brand aligned"
          changeType="positive"
          icon={<Image className="w-5 h-5 text-[#287C7A]" />}
        />
        <MetricCard
          title="Pending Approvals"
          value="3"
          change="Action Required"
          changeType="negative"
          icon={<CheckSquare className="w-5 h-5 text-[#C98216]" />}
        />
        <MetricCard
          title="Published This Month"
          value="27"
          change="+18.4% reach"
          changeType="positive"
          icon={<Send className="w-5 h-5 text-[#16855B]" />}
        />
      </div>

      {/* Needs Your Attention Section */}
      <div>
        <h2 className="text-lg font-bold text-[#17202A] mb-4 flex items-center gap-2">
          <Clock className="w-5 h-5 text-[#C98216]" /> Needs Your Attention
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
          {/* Card 1 */}
          <Card className="border-l-4 border-l-[#C98216] flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-bold uppercase tracking-wider text-[#C98216]">Approvals</span>
                <span className="text-xs text-[#667085]">Today</span>
              </div>
              <h3 className="text-base font-bold text-[#17202A]">3 Approvals Waiting</h3>
              <p className="text-xs text-[#667085] mt-1">Summer Dining Campaign assets generated by Creative Director AI.</p>
            </div>
            <div className="mt-4 pt-3 border-t border-[#E4E7EC] flex justify-end">
              <Button
                variant="outline"
                size="sm"
                rightIcon={<ArrowRight className="w-3.5 h-3.5" />}
                onClick={() => navigate('/approvals')}
              >
                Review Assets
              </Button>
            </div>
          </Card>

          {/* Card 2 */}
          <Card className="border-l-4 border-l-[#287C7A] flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-bold uppercase tracking-wider text-[#287C7A]">Publishing</span>
                <span className="text-xs text-[#667085]">Scheduled Today</span>
              </div>
              <h3 className="text-base font-bold text-[#17202A]">2 Scheduled Posts</h3>
              <p className="text-xs text-[#667085] mt-1">Instagram + Facebook posts for Sunday Brunch set for 10:00 AM.</p>
            </div>
            <div className="mt-4 pt-3 border-t border-[#E4E7EC] flex justify-end">
              <Button
                variant="outline"
                size="sm"
                rightIcon={<ArrowRight className="w-3.5 h-3.5" />}
                onClick={() => navigate('/publishing')}
              >
                View Publishing
              </Button>
            </div>
          </Card>

          {/* Card 3 */}
          <Card className="border-l-4 border-l-[#5B5BD6] flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-bold uppercase tracking-wider text-[#5B5BD6]">AI Insight</span>
                <AIBadge roleName="Performance Analyst" />
              </div>
              <h3 className="text-base font-bold text-[#17202A]">Weekend Outperformance</h3>
              <p className="text-xs text-[#667085] mt-1">Weekend culinary content is outperforming weekday posts by +31%.</p>
            </div>
            <div className="mt-4 pt-3 border-t border-[#E4E7EC] flex justify-end">
              <Button
                variant="outline"
                size="sm"
                rightIcon={<ArrowRight className="w-3.5 h-3.5" />}
                onClick={() => navigate('/insights')}
              >
                View Insight
              </Button>
            </div>
          </Card>
        </div>
      </div>

      {/* Two Column Layout: Activity & AI Recommendations */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left 2 Cols: Activity Timeline */}
        <div className="lg:col-span-2 space-y-4">
          <Card>
            <CardHeader
              title="Marketing Activity Timeline"
              subtitle="End-to-end traceability of brand, campaign, and governance events"
              action={
                <Button variant="ghost" size="sm" onClick={() => navigate('/audit')}>
                  View Full Audit Log
                </Button>
              }
            />
            <div className="space-y-4">
              {mockAuditLogs.map((log) => (
                <div key={log.id} className="flex items-start gap-4 p-3 rounded-lg hover:bg-[#F7F8FA] transition-colors border border-[#E4E7EC]">
                  <div className="p-2 rounded-lg bg-[#F0F0FF] text-[#5B5BD6] mt-0.5">
                    {log.actorType === 'AI' ? <Sparkles className="w-4 h-4" /> : <CheckCircle2 className="w-4 h-4 text-[#16855B]" />}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-bold text-[#17202A]">{log.actor}</span>
                        {log.aiRole && <AIBadge roleName={log.aiRole} />}
                      </div>
                      <span className="text-[11px] text-[#667085]">{log.timestamp}</span>
                    </div>
                    <p className="text-xs text-[#17202A] font-semibold mt-1">{log.action}: {log.artifact}</p>
                    {log.details?.businessJustification && (
                      <p className="text-xs text-[#667085] mt-0.5">{log.details.businessJustification}</p>
                    )}
                  </div>
                  <StatusBadge status={log.result} />
                </div>
              ))}
            </div>
          </Card>
        </div>

        {/* Right Col: AI Recommendations */}
        <div className="space-y-4">
          <Card className="border-t-4 border-t-[#5B5BD6]">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-base font-bold text-[#17202A] flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-[#5B5BD6]" /> AI Strategic Recommendations
              </h3>
              <AIBadge roleName="Performance Analyst" />
            </div>

            <div className="space-y-4">
              {mockRecommendations.map((rec) => (
                <div key={rec.id} className="p-4 rounded-xl border border-[#E4E7EC] bg-[#F7F8FA] space-y-2">
                  <h4 className="text-xs font-bold text-[#17202A]">{rec.title}</h4>
                  <p className="text-xs text-[#667085]"><span className="font-semibold text-[#17202A]">Why:</span> {rec.why}</p>
                  <p className="text-xs text-[#667085]"><span className="font-semibold text-[#17202A]">Impact:</span> {rec.businessImpact}</p>
                  
                  <div className="pt-2 flex items-center justify-between border-t border-[#E4E7EC]">
                    <span className="text-[10px] text-[#5B5BD6] font-medium">Evidence: {rec.evidence}</span>
                    <Button
                      variant="ai"
                      size="sm"
                      onClick={() => navigate('/recommendations')}
                    >
                      Review
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
};
